### ISSUE TITLE
Correct? - You have an unlabeled element or control...

### ISSUE THREAD

**Issue by crwang** [reactjs/react-a11y#107]
Hi,

I'm getting a message about failing validation but I think I'm following the proper convention:

Basically, I have a `label` and a `textarea` and have a `for` in the `label` and an `id` in the `textarea`, but I'm getting this message:

"You have an unlabeled element or control. Add `aria-label` or `aria-labelledby` attribute, or put some text in the element."

I think my HTML markup is correct, but maybe not?  Does anyone have any advice on this? 

I'm also attaching a screenshot:

![image](https://cloud.githubusercontent.com/assets/1487444/12173580/34b6f4b6-b51d-11e5-9fdd-a584f76a8132.png)

**Comment by dspnorman** [comment]
Just ran react-a11y for the first time, and got this same message.

I'm also confident that my markup is correct, semantic, and accessible.

If you look closely, you'll notice that react-a11y appears to be rewriting the IDs of your inputs and textareas, breaking the association with their labels. This seems like a serious bug to me.

**Comment by VladShcherbin** [comment]
+1, a11y changes id so it becomes invalid

**Comment by jdan** [comment]
Hey all, I have a fix for this on my fork: https://github.com/jdan/react-a11y/commit/ee970693b3cbfbf8d55a9c3a7589ccd3cb9c2633

I'm having a remarkably difficult time writing tests for it, though, since the audit needs to run after the component mounts (you'll see in the commit that I hack some login onto the `ref` attribute), and the testing infrastructure is meant to run after `createElement` (synchronously)

https://github.com/jdan/react-a11y/commit/973aa43a02711e041ebed03cdf9327be45f6cda8 shows my attempts to test my code - lots of good progress! But I'm getting stumped at this test (https://github.com/jdan/react-a11y/commit/973aa43a02711e041ebed03cdf9327be45f6cda8#diff-c3c2e5784ba4c10e75ef234a6ab0255cR510) because it seems the `ref` callback sometimes fires after `componentDidMount`.

**Comment by fernandopasik** [comment]
I'm having the same issue with input elements

> input#first-name You have an unlabeled element or control. Add `aria-label` or `aria-labelledby` attribute, or put some text in the element.

``` html
<div class="field" id="a11y-8931">
    <label for="first-name" id="a11y-8930">
        First Name
        <input id="first-name" name="first-name"/>
    </label>
</div>
```

**Comment by crwang** [comment]
Well, it's been several months and there hasn't been much change on this. 

We decided to go with http://www.deque.com/products/axe/ and have been really happy with that.

https://github.com/dequelabs/axe-core

I'm going to close this out.

**Comment by jdan** [comment]
@crwang Be sure to check out their react offering as well - https://github.com/dylanb/react-axe
