### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by levithomason** [reactjs/react-a11y#126]
We're looking for an a11y solution over at [Semantic-Org/Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React).  We're considering `eslint-plugin-jsx-a11y`, though I'd prefer to use what `react-a11y` offers.

Judging from the issues/PRs and contributions, it looks like this project may be on its last leg.  Is this an accurate assessment or are there intentions to more actively maintain this project moving forward?

Thanks much!

**Comment by erin-doyle** [comment]
No answer on this yet?  That sounds problematic...

**Comment by erin-doyle** [comment]
After some looking myself @levithomason I would suggest the following (though since you posted this so long ago you've probably already figured something out...):

[eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y) is just a linting tool, not a runtime tool, and the intent as detailed in the repo is to be used in _conjunction_ with react-a11y, not as a replacement.

That being said, it does look like this repo is not longer being maintained which is sad 😢 but there is a fork that seems to be much better supported and has resolved a lot of the open issues listed here: [romeovs/react-a11y](https://github.com/romeovs/react-a11y).

**Comment by wyattdanger** [comment]
Can only speak for myself here, I have shifted my focus away from this project and use eslint-plugin-jsx-a11y in addition to axe-core for a11y testing at work

**Comment by levithomason** [comment]
Thanks much folks!  We also went with `eslint-plugin-jsx-a11y`.  Will close this and consider the case closed.
